import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion } from "motion/react";
import { Shield, Users, Zap, Radio, Navigation, Clock, FileText, Heart, Siren, MapPin } from "lucide-react";
import { containerVariants, slideUp } from "../shared/animations";
import { Badge, GlassCard, SeverityDot } from "../shared/primitives";
import { AppLayout } from "../shared/layout";
import { incidents, } from "../data/mockData";
// ─── EMERGENCY RESPONSE ───
export function EmergencyPage({ setPage }) {
    const [alertLevel, setAlertLevel] = useState("elevated");
    const alertColors = {
        normal: { bg: "rgba(16,185,129,0.08)", border: "rgba(16,185,129,0.25)", text: "#34d399", badge: "green" },
        elevated: { bg: "rgba(245,158,11,0.08)", border: "rgba(245,158,11,0.25)", text: "#fbbf24", badge: "amber" },
        critical: { bg: "rgba(239,68,68,0.1)", border: "rgba(239,68,68,0.3)", text: "#f87171", badge: "red" },
    };
    const ac = alertColors[alertLevel];
    return (_jsx(AppLayout, { page: "emergency", setPage: setPage, title: "Emergency Response Center", subtitle: "24/7 \u00B7 AI-Coordinated \u00B7 14 Units Deployed", children: _jsxs(motion.div, { variants: containerVariants, initial: "hidden", animate: "visible", className: "space-y-5", children: [_jsxs(motion.div, { variants: slideUp, className: "p-4 rounded-2xl flex items-center gap-3 relative overflow-hidden", style: { background: ac.bg, border: `1px solid ${ac.border}` }, animate: { boxShadow: alertLevel === "critical" ? "0 0 30px rgba(239,68,68,0.2)" : "0 0 0px rgba(239,68,68,0)" }, children: [alertLevel === "critical" && _jsx("div", { className: "absolute inset-0 scan-container pointer-events-none" }), _jsx("div", { className: "w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0", style: { background: `${ac.text}18` }, children: _jsx(Siren, { size: 18, style: { color: ac.text } }) }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "font-display font-bold text-sm", style: { color: ac.text }, children: ["Alert Level: ", alertLevel.toUpperCase()] }), _jsx("div", { className: "text-xs text-slate-500 font-mono-code", children: "3 active incidents \u00B7 Medical team on standby \u00B7 All exits operational" })] }), _jsx("div", { className: "flex gap-1.5 p-1 glass rounded-xl", children: ["normal", "elevated", "critical"].map(l => (_jsx(motion.button, { whileTap: { scale: 0.97 }, onClick: () => setAlertLevel(l), className: `px-2.5 py-1 rounded-lg text-xs font-semibold capitalize transition-all ${alertLevel === l ? "text-white" : "text-slate-600 hover:text-slate-400"}`, style: alertLevel === l ? { background: alertColors[l].text + "30" } : {}, children: l }, l))) })] }), _jsxs("div", { className: "grid grid-cols-12 gap-5", children: [_jsx(motion.div, { variants: slideUp, className: "col-span-12 md:col-span-5", children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h3", { className: "font-display text-white font-semibold", children: "Active Incidents" }), _jsx(Badge, { color: "red", children: "3 Open" })] }), _jsx("div", { className: "space-y-2.5", children: incidents.map((inc, i) => (_jsxs(motion.div, { initial: { opacity: 0, x: -16 }, animate: { opacity: 1, x: 0 }, transition: { delay: i * 0.07 }, className: `p-4 rounded-xl border transition-all ${inc.status !== "resolved"
                                                ? "border-red-500/15" : "border-indigo-500/[0.04] opacity-40"}`, style: inc.status !== "resolved" ? { background: "rgba(239,68,68,0.04)" } : { background: "rgba(99,102,241,0.02)" }, children: [_jsxs("div", { className: "flex items-center justify-between mb-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(SeverityDot, { severity: inc.severity }), _jsx("span", { className: "text-white font-semibold text-sm", children: inc.type })] }), _jsx("span", { className: "font-mono-code text-xs text-slate-600", children: inc.time })] }), _jsx("div", { className: "text-xs text-slate-500 mb-2 font-mono-code", children: inc.location }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Badge, { color: inc.status === "resolved" ? "green" : inc.status === "responding" ? "red" : "amber", children: inc.status }), _jsx("span", { className: "text-xs text-slate-700 font-mono-code", children: inc.id })] })] }, inc.id))) })] }) }), _jsxs("div", { className: "col-span-12 md:col-span-7 space-y-5", children: [_jsx(motion.div, { variants: slideUp, children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Navigation, { size: 15, className: "text-indigo-400" }), _jsx("h3", { className: "font-display text-white font-semibold", children: "Evacuation Routes" })] }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: [
                                                    { route: "Route Alpha", exits: "Gates A, B", est: "8 min", capacity: "25,000/hr", status: "clear" },
                                                    { route: "Route Beta", exits: "Gates C, D", est: "11 min", capacity: "18,000/hr", status: "congested" },
                                                    { route: "Route Gamma", exits: "Gates E, F", est: "7 min", capacity: "22,000/hr", status: "clear" },
                                                    { route: "Route Delta", exits: "Emergency X1–X4", est: "4 min", capacity: "8,000/hr", status: "standby" },
                                                ].map(({ route, exits, est, capacity, status }) => (_jsxs(motion.div, { whileHover: { y: -2 }, className: "glass rounded-xl p-4 border border-indigo-500/[0.06] hover:border-indigo-500/[0.2] transition-all", children: [_jsxs("div", { className: "flex items-center justify-between mb-1.5", children: [_jsx("span", { className: "font-display text-white font-semibold text-sm", children: route }), _jsx(Badge, { color: status === "clear" ? "green" : status === "congested" ? "red" : "amber", children: status })] }), _jsx("div", { className: "text-xs text-slate-500 font-mono-code mb-2", children: exits }), _jsxs("div", { className: "flex gap-3 text-xs text-slate-600 font-mono-code", children: [_jsxs("span", { children: [_jsx(Clock, { size: 9, className: "inline mr-1" }), est] }), _jsxs("span", { children: [_jsx(Users, { size: 9, className: "inline mr-1" }), capacity] })] })] }, route))) })] }) }), _jsx(motion.div, { variants: slideUp, children: _jsxs(GlassCard, { className: "p-5", children: [_jsx("h3", { className: "font-display text-white font-semibold mb-4", children: "Emergency Actions" }), _jsx("div", { className: "grid grid-cols-3 gap-2.5", children: [
                                                    { label: "Full Evacuation", icon: Navigation, color: "#ef4444" },
                                                    { label: "Medical Code", icon: Heart, color: "#ef4444" },
                                                    { label: "Police Alert", icon: Shield, color: "#ef4444" },
                                                    { label: "PA Broadcast", icon: Radio, color: "#f59e0b" },
                                                    { label: "Safe Zones", icon: MapPin, color: "#6366f1" },
                                                    { label: "Incident Log", icon: FileText, color: "#64748b" },
                                                ].map(({ label, icon: Icon, color }) => (_jsxs(motion.button, { whileHover: { scale: 1.04, y: -3 }, whileTap: { scale: 0.96 }, className: "flex flex-col items-center gap-2 p-4 rounded-xl border text-xs font-semibold transition-all font-display cursor-pointer", style: { background: `${color}08`, border: `1px solid ${color}20`, color: `${color}cc` }, children: [_jsx(Icon, { size: 20 }), _jsx("span", { className: "text-center leading-tight", children: label })] }, label))) })] }) }), _jsx(motion.div, { variants: slideUp, children: _jsxs(GlassCard, { className: "p-5", style: { border: "1px solid rgba(99,102,241,0.15)" }, children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx("div", { className: "w-7 h-7 rounded-lg flex items-center justify-center", style: { background: "linear-gradient(135deg, #6366f1, #4f46e5)" }, children: _jsx(Zap, { size: 13, className: "text-white" }) }), _jsx("h3", { className: "font-display text-white font-semibold text-sm", children: "AI Emergency Summary" }), _jsx("div", { className: "ml-auto text-xs text-slate-600 font-mono-code", children: "Updated 16:42:08" })] }), _jsxs("div", { className: "glass rounded-xl p-4 text-sm text-slate-400 leading-relaxed border border-indigo-500/[0.08]", children: ["Current threat level is ", _jsx("span", { className: "text-amber-400 font-bold", children: "ELEVATED" }), ". Medical incident in Section C is being handled \u2014 ETA 2 minutes. Gate C congestion elevated but manageable with current protocols. No structural threats identified. Recommend deploying 2 additional stewards to Gate C. All emergency exits clear and operational."] })] }) })] })] })] }) }));
}
