import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Map, MessageSquare, Leaf, ChevronRight, Send, X, Zap, Coffee, Accessibility, Phone, Train } from "lucide-react";
import { containerVariants, itemVariants } from "../shared/animations";
import { Badge, GlassCard, LiveBadge } from "../shared/primitives";
import { AppLayout } from "../shared/layout";
import { chatMessages, } from "../data/mockData";
import { useAssistantChat } from "../features/stadium-assistant/useAssistantChat";
import { useAccessibility } from "../lib/accessibility/AccessibilityContext";
// ─── FAN DASHBOARD ───
export function FanDashboard({ setPage }) {
    const [chatOpen, setChatOpen] = useState(false);
    const [msg, setMsg] = useState("");
    const { language } = useAccessibility();
    const { messages, sendMessage: sendToAssistant, isLoading: isTyping, error } = useAssistantChat(chatMessages, language);
    const sendMsg = () => {
        if (!msg.trim())
            return;
        const text = msg;
        setMsg("");
        void sendToAssistant(text);
    };
    const quickActions = [
        { icon: Map, label: "Stadium Map", page: "map", color: "#6366f1" },
        { icon: Train, label: "Transport", page: "transport", color: "#06b6d4" },
        { icon: Coffee, label: "Food & Drink", page: "fan", color: "#f59e0b" },
        { icon: Accessibility, label: "Accessibility", page: "accessibility", color: "#8b5cf6" },
    ];
    return (_jsxs(AppLayout, { page: "fan", setPage: setPage, title: "Fan Dashboard", subtitle: "Welcome back, Jamie \u00B7 Lusail Stadium \u00B7 Match Day", children: [_jsxs(motion.div, { variants: containerVariants, initial: "hidden", animate: "visible", className: "grid grid-cols-12 gap-5", children: [_jsxs("div", { className: "col-span-12 md:col-span-8 space-y-5", children: [_jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-6 relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 pointer-events-none", style: { background: "radial-gradient(ellipse at 100% 0%, rgba(99,102,241,0.08), transparent 60%)" } }), _jsxs("div", { className: "flex items-start justify-between relative", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(LiveBadge, {}), _jsx("span", { className: "text-slate-500 text-xs font-mono-code", children: "Match Day Active" })] }), _jsx("h2", { className: "font-display text-2xl font-bold gradient-text-primary", children: "Good afternoon, Jamie!" }), _jsxs("p", { className: "text-slate-500 text-sm mt-1.5", children: ["Kickoff in ", _jsx("span", { className: "text-amber-400 font-bold font-mono-code", children: "45 minutes" }), ". Your experience is ready."] })] }), _jsx("img", { src: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=120&h=80&fit=crop&auto=format", alt: "Stadium", className: "rounded-xl w-24 h-16 object-cover opacity-60" })] })] }) }), _jsx(motion.div, { variants: itemVariants, children: _jsxs("div", { className: "rounded-2xl p-6 relative overflow-hidden", style: {
                                        background: "linear-gradient(135deg, rgba(99,102,241,0.15), rgba(139,92,246,0.1))",
                                        border: "1px solid rgba(99,102,241,0.2)",
                                        boxShadow: "0 0 40px rgba(99,102,241,0.08)"
                                    }, children: [_jsx("div", { className: "absolute inset-0 pointer-events-none", style: { background: "radial-gradient(ellipse at 0% 0%, rgba(99,102,241,0.15), transparent 60%)" } }), _jsx("div", { className: "absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-indigo-500/50 to-transparent" }), _jsxs("div", { className: "relative flex items-start justify-between mb-4", children: [_jsxs("div", { children: [_jsx(Badge, { color: "indigo", children: "FIFA World Cup 2026" }), _jsx("h3", { className: "font-display text-white font-bold text-2xl mt-2", children: "Morocco vs. Portugal" }), _jsx("p", { className: "text-slate-400 text-sm", children: "Lusail Iconic Stadium \u00B7 Qatar" })] }), _jsxs("div", { className: "text-right", children: [_jsx("div", { className: "font-display text-3xl font-black gradient-text-indigo font-mono-code", children: "K-14" }), _jsx("div", { className: "text-slate-500 text-xs font-mono-code", children: "Row 8 \u00B7 Seat 22" })] })] }), _jsx("div", { className: "grid grid-cols-3 gap-4 pt-4 border-t border-indigo-500/[0.12]", children: [["Date", "Jul 14, 2026"], ["Kickoff", "18:00 AST"], ["Gate", "Gate H · Open"]].map(([k, v]) => (_jsxs("div", { children: [_jsx("div", { className: "text-xs text-slate-500 font-mono-code", children: k }), _jsx("div", { className: "text-white text-sm font-semibold mt-0.5", children: v })] }, k))) })] }) }), _jsx(motion.div, { variants: containerVariants, className: "grid grid-cols-4 gap-3", children: quickActions.map(({ icon: Icon, label, page: p, color }) => (_jsxs(motion.button, { variants: itemVariants, whileHover: { y: -6, scale: 1.04 }, whileTap: { scale: 0.96 }, onClick: () => setPage(p), transition: { type: "spring", stiffness: 400, damping: 20 }, className: "glass rounded-2xl p-4 flex flex-col items-center gap-3 card-glow group relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none", style: { background: `radial-gradient(ellipse at 50% 0%, ${color}15, transparent 70%)` } }), _jsx("div", { className: "w-10 h-10 rounded-xl flex items-center justify-center transition-transform group-hover:scale-110 duration-300", style: { background: `${color}15`, color }, children: _jsx(Icon, { size: 18 }) }), _jsx("span", { className: "text-xs text-slate-400 font-medium group-hover:text-slate-200 transition-colors", children: label })] }, label))) }), _jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h3", { className: "font-display text-white font-semibold", children: "Live Crowd Density" }), _jsx(LiveBadge, {})] }), _jsx("div", { className: "grid grid-cols-8 gap-1 mb-3", children: Array.from({ length: 64 }, (_, i) => {
                                                const intensity = 0.2 + (Math.sin(i * 0.8) + 1) / 2 * 0.8;
                                                const bg = intensity > 0.8 ? "#ef4444" : intensity > 0.6 ? "#f59e0b" : intensity > 0.4 ? "#eab308" : intensity > 0.2 ? "#10b981" : "#1e293b";
                                                return (_jsx(motion.div, { initial: { opacity: 0, scale: 0 }, animate: { opacity: intensity * 0.85 + 0.15, scale: 1 }, transition: { delay: i * 0.008, duration: 0.3 }, className: "h-6 rounded-sm", style: { background: bg } }, i));
                                            }) }), _jsx("div", { className: "flex items-center gap-4 text-xs text-slate-500", children: [["#10b981", "Low"], ["#eab308", "Medium"], ["#f59e0b", "High"], ["#ef4444", "Critical"]].map(([c, l]) => (_jsxs("div", { className: "flex items-center gap-1.5", children: [_jsx("div", { className: "w-3 h-2 rounded-sm", style: { background: c } }), l] }, l))) })] }) })] }), _jsxs("div", { className: "col-span-12 md:col-span-4 space-y-4", children: [_jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("span", { className: "font-display text-white font-semibold text-sm", children: "Eco Score" }), _jsx(Leaf, { size: 14, className: "text-emerald-400" })] }), _jsxs("div", { className: "font-display text-4xl font-black text-emerald-400 mb-1", children: ["84", _jsx("span", { className: "text-xl text-slate-600", children: "/100" })] }), _jsx("div", { className: "text-xs text-slate-500 mb-3", children: "You used public transport \u2014 great choice!" }), _jsx("div", { className: "h-1.5 rounded-full", style: { background: "rgba(16,185,129,0.15)" }, children: _jsx(motion.div, { initial: { width: 0 }, animate: { width: "84%" }, transition: { duration: 1.2, ease: "easeOut", delay: 0.5 }, className: "h-full rounded-full", style: { background: "linear-gradient(90deg, #10b981, #34d399)" } }) })] }) }), _jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("span", { className: "font-display text-white font-semibold text-sm", children: "Nearby Food" }), _jsx("span", { className: "text-xs text-indigo-400 cursor-pointer hover:text-indigo-300 transition-colors", children: "See all" })] }), _jsx("div", { className: "space-y-2", children: [
                                                { name: "Al Rayyan Grill", wait: "4 min", type: "Local Cuisine", dist: "120m" },
                                                { name: "Fan Zone Burger", wait: "8 min", type: "Fast Food", dist: "200m" },
                                                { name: "Oasis Café", wait: "2 min", type: "Beverages", dist: "80m" },
                                            ].map(({ name, wait, type, dist }) => (_jsxs(motion.div, { whileHover: { x: 3 }, className: "flex items-center justify-between py-2.5 border-b border-indigo-500/[0.06] last:border-0 cursor-pointer", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm text-white font-medium", children: name }), _jsxs("div", { className: "text-xs text-slate-600 font-mono-code", children: [type, " \u00B7 ", dist] })] }), _jsx(Badge, { color: "green", children: wait })] }, name))) })] }) }), _jsx(motion.div, { variants: itemVariants, children: _jsxs(motion.button, { whileHover: { scale: 1.02, y: -2 }, whileTap: { scale: 0.98 }, onClick: () => setPage("emergency"), className: "w-full rounded-2xl p-4 flex items-center gap-3 transition-all cursor-pointer relative overflow-hidden group", style: { background: "rgba(239,68,68,0.06)", border: "1px solid rgba(239,68,68,0.2)" }, children: [_jsx("div", { className: "absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300", style: { background: "radial-gradient(ellipse at 50% 50%, rgba(239,68,68,0.08), transparent 70%)" } }), _jsxs("div", { className: "w-10 h-10 rounded-xl flex items-center justify-center text-red-400 relative", style: { background: "rgba(239,68,68,0.1)" }, children: [_jsx(Phone, { size: 17 }), _jsx("span", { className: "absolute -top-1 -right-1 w-2.5 h-2.5 rounded-full bg-red-500", children: _jsx("span", { className: "absolute inset-0 rounded-full bg-red-500 animate-ping opacity-75" }) })] }), _jsxs("div", { className: "text-left", children: [_jsx("div", { className: "text-red-300 font-semibold text-sm font-display", children: "Emergency Help" }), _jsx("div", { className: "text-slate-600 text-xs font-mono-code", children: "24/7 rapid response" })] }), _jsx(ChevronRight, { size: 15, className: "ml-auto text-red-400/50 group-hover:text-red-400 group-hover:translate-x-1 transition-all" })] }) })] })] }), _jsx(AnimatePresence, { children: !chatOpen && (_jsx(motion.button, { initial: { scale: 0, opacity: 0 }, animate: { scale: 1, opacity: 1 }, exit: { scale: 0, opacity: 0 }, whileHover: { scale: 1.1 }, whileTap: { scale: 0.9 }, onClick: () => setChatOpen(true), className: "fixed bottom-6 right-6 w-14 h-14 rounded-2xl flex items-center justify-center text-white z-50", style: {
                        background: "linear-gradient(135deg, #6366f1, #4f46e5)",
                        boxShadow: "0 0 30px rgba(99,102,241,0.4), 0 0 60px rgba(99,102,241,0.15)"
                    }, children: _jsx(MessageSquare, { size: 22 }) })) }), _jsx(AnimatePresence, { children: chatOpen && (_jsxs(motion.div, { initial: { opacity: 0, scale: 0.9, y: 20 }, animate: { opacity: 1, scale: 1, y: 0 }, exit: { opacity: 0, scale: 0.9, y: 20 }, transition: { type: "spring", stiffness: 300, damping: 25 }, className: "fixed bottom-6 right-6 w-96 h-[500px] glass-bright rounded-2xl flex flex-col z-50 overflow-hidden", style: { boxShadow: "0 0 0 1px rgba(99,102,241,0.2), 0 30px 80px rgba(0,0,0,0.6), 0 0 60px rgba(99,102,241,0.1)" }, children: [_jsxs("div", { className: "flex items-center justify-between px-4 py-3 border-b border-indigo-500/[0.1]", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-7 h-7 rounded-lg flex items-center justify-center", style: { background: "linear-gradient(135deg, #6366f1, #8b5cf6)" }, children: _jsx(Zap, { size: 13, className: "text-white" }) }), _jsxs("div", { children: [_jsx("div", { className: "text-white text-sm font-display font-semibold", children: "AIZA Assistant" }), _jsxs("div", { className: "text-xs text-emerald-400 font-mono-code flex items-center gap-1", children: [_jsx("span", { className: "w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse inline-block" }), " Online"] })] })] }), _jsx(motion.button, { whileHover: { scale: 1.1 }, onClick: () => setChatOpen(false), className: "text-slate-500 hover:text-white transition-colors", children: _jsx(X, { size: 15 }) })] }), _jsxs("div", { className: "flex-1 overflow-y-auto p-4 space-y-3", role: "log", "aria-live": "polite", children: [messages.map((m, i) => (_jsx(motion.div, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: i * 0.05 }, className: `flex ${m.role === "user" ? "justify-end" : "justify-start"}`, children: _jsx("div", { className: `max-w-[80%] px-3 py-2 rounded-xl text-sm leading-relaxed ${m.role === "user"
                                            ? "text-white" : "glass text-slate-300 border border-indigo-500/[0.08]"}`, style: m.role === "user" ? { background: "linear-gradient(135deg, #6366f1, #4f46e5)" } : {}, children: m.text }) }, i))), isTyping && (_jsx(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, className: "flex justify-start", children: _jsx("div", { className: "glass border border-indigo-500/[0.08] px-3 py-2 rounded-xl flex items-center gap-1", children: [0, 1, 2].map(i => (_jsx(motion.div, { animate: { y: [0, -3, 0] }, transition: { duration: 0.6, repeat: Infinity, delay: i * 0.15 }, className: "w-1 h-1 rounded-full bg-indigo-400" }, i))) }) })), error && (_jsx("p", { role: "alert", className: "text-xs text-rose-400 font-mono-code text-center py-1", children: error }))] }), _jsx("form", { onSubmit: (e) => { e.preventDefault(); sendMsg(); }, className: "p-3 border-t border-indigo-500/[0.08]", children: _jsxs("div", { className: "flex gap-2", children: [_jsx("label", { htmlFor: "dashboard-chat-input", className: "sr-only", children: "Ask AIZA anything" }), _jsx("input", { id: "dashboard-chat-input", value: msg, onChange: e => setMsg(e.target.value), placeholder: "Ask AIZA anything...", className: "flex-1 glass border border-indigo-500/[0.1] rounded-xl px-3 py-2 text-sm text-white placeholder-slate-600 outline-none focus:border-indigo-500/40 transition-colors" }), _jsx(motion.button, { type: "submit", whileHover: { scale: 1.05 }, whileTap: { scale: 0.95 }, disabled: isTyping || !msg.trim(), className: "w-9 h-9 rounded-xl flex items-center justify-center text-white transition-colors", style: { background: "linear-gradient(135deg, #6366f1, #4f46e5)" }, children: _jsx(Send, { size: 14 }) })] }) })] })) })] }));
}
