import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "motion/react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { Leaf, Zap, Car, Train, Droplets, Recycle, Wind } from "lucide-react";
import { containerVariants, slideUp } from "../shared/animations";
import { chartTooltipStyle } from "../shared/chartTheme";
import { KpiCard, GlassCard } from "../shared/primitives";
import { AppLayout } from "../shared/layout";
import { carbonData, } from "../data/mockData";
// ─── SUSTAINABILITY ───
export function SustainabilityPage({ setPage }) {
    return (_jsx(AppLayout, { page: "sustainability", setPage: setPage, title: "Sustainability Dashboard", subtitle: "FIFA 2026 Green Goals \u00B7 Carbon Neutral Target", children: _jsxs(motion.div, { variants: containerVariants, initial: "hidden", animate: "visible", className: "space-y-5", children: [_jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4", children: [_jsx(KpiCard, { label: "Carbon Saved Today", value: "42t CO\u2082", change: "+8%", icon: Leaf, color: "green" }), _jsx(KpiCard, { label: "Green Transport", value: "74%", change: "+3%", icon: Train, color: "cyan" }), _jsx(KpiCard, { label: "Waste Recycled", value: "68%", icon: Recycle, color: "green" }), _jsx(KpiCard, { label: "Water Refills", value: "12,440", change: "+24%", icon: Droplets, color: "indigo" })] }), _jsxs("div", { className: "grid grid-cols-12 gap-5", children: [_jsx(motion.div, { variants: slideUp, className: "col-span-12 md:col-span-8", children: _jsxs(GlassCard, { className: "p-5", children: [_jsx("h3", { className: "font-display text-white font-semibold mb-4", children: "Eco Score Trend \u2014 This Week" }), _jsx(ResponsiveContainer, { width: "100%", height: 220, children: _jsxs(LineChart, { data: carbonData, children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "rgba(99,102,241,0.06)" }), _jsx(XAxis, { dataKey: "day", tick: { fill: "#475569", fontSize: 10, fontFamily: "JetBrains Mono" }, axisLine: false, tickLine: false }), _jsx(YAxis, { domain: [50, 100], tick: { fill: "#475569", fontSize: 10, fontFamily: "JetBrains Mono" }, axisLine: false, tickLine: false }), _jsx(Tooltip, { contentStyle: chartTooltipStyle }), _jsx(Line, { isAnimationActive: false, type: "monotone", dataKey: "score", stroke: "#10b981", strokeWidth: 2.5, dot: { fill: "#10b981", r: 5, strokeWidth: 0 } })] }) })] }) }), _jsx(motion.div, { variants: slideUp, className: "col-span-12 md:col-span-4", children: _jsxs(GlassCard, { className: "p-5 h-full", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx("div", { className: "w-7 h-7 rounded-lg flex items-center justify-center", style: { background: "rgba(16,185,129,0.15)" }, children: _jsx(Zap, { size: 13, className: "text-emerald-400" }) }), _jsx("h3", { className: "font-display text-white font-semibold text-sm", children: "AI Eco Recommendations" })] }), _jsx("div", { className: "space-y-2.5", children: [
                                            { text: "Deploy 8 more water refill stations near Gate C to reduce plastic waste by ~18%.", icon: Droplets, c: "#06b6d4" },
                                            { text: "Shift 12% of parking to EV-only bays to incentivize electric vehicles.", icon: Car, c: "#10b981" },
                                            { text: "Food waste above target. Suggest 10% batch reduction in concessions.", icon: Recycle, c: "#f59e0b" },
                                            { text: "Fan Zone 3 energy 22% above baseline. Check HVAC scheduling.", icon: Wind, c: "#8b5cf6" },
                                        ].map(({ text, icon: Icon, c }, i) => (_jsxs(motion.div, { initial: { opacity: 0, x: 10 }, animate: { opacity: 1, x: 0 }, transition: { delay: i * 0.1 }, className: "flex gap-3 p-3 rounded-xl text-xs", style: { background: `${c}08`, border: `1px solid ${c}15` }, children: [_jsx(Icon, { size: 13, style: { color: c }, className: "flex-shrink-0 mt-0.5" }), _jsx("span", { className: "text-slate-400 leading-relaxed", children: text })] }, i))) })] }) }), _jsx(motion.div, { variants: slideUp, className: "col-span-12", children: _jsxs(GlassCard, { className: "p-5", children: [_jsx("h3", { className: "font-display text-white font-semibold mb-4", children: "Waste Management by Zone" }), _jsx("div", { className: "grid grid-cols-3 md:grid-cols-6 gap-3", children: ["Gate A", "Gate B", "Fan Zone 1", "Fan Zone 2", "Concessions", "Parking"].map((zone, i) => {
                                            const pct = [72, 81, 64, 58, 55, 43][i] ?? 0;
                                            const color = pct >= 70 ? "#10b981" : pct >= 55 ? "#f59e0b" : "#ef4444";
                                            return (_jsxs("div", { className: "glass rounded-xl p-3 text-center border border-indigo-500/[0.06]", children: [_jsxs("div", { className: "font-display text-lg font-bold text-white", children: [pct, "%"] }), _jsx("div", { className: "text-xs text-slate-600 mb-2 font-mono-code", children: zone }), _jsx("div", { className: "h-1 rounded-full", style: { background: `${color}15` }, children: _jsx(motion.div, { initial: { width: 0 }, animate: { width: `${pct}%` }, transition: { duration: 1, delay: i * 0.1 }, className: "h-full rounded-full", style: { background: color } }) })] }, zone));
                                        }) })] }) })] })] }) }));
}
