import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion } from "motion/react";
import { Leaf, ArrowRight, Clock, Car, Train, Bus, Bike } from "lucide-react";
import { containerVariants, itemVariants, slideUp } from "../shared/animations";
import { Badge, GlassCard, LiveBadge } from "../shared/primitives";
import { AppLayout } from "../shared/layout";
// ─── TRANSPORT HUB ───
export function TransportPage({ setPage }) {
    const [mode, setMode] = useState("metro");
    const modes = [
        { id: "metro", icon: Train, label: "Metro" },
        { id: "bus", icon: Bus, label: "Bus" },
        { id: "taxi", icon: Car, label: "Taxi/Ride" },
        { id: "bike", icon: Bike, label: "Bike" },
    ];
    const departures = [
        { line: "Red Line", from: "Doha Airport", dep: "16:45", arr: "17:12", crowd: "high" },
        { line: "Gold Line", from: "Msheireb", dep: "16:50", arr: "17:18", crowd: "medium" },
        { line: "Green Line", from: "Al Sadd", dep: "17:00", arr: "17:22", crowd: "low" },
    ];
    return (_jsx(AppLayout, { page: "transport", setPage: setPage, title: "Transport Hub", subtitle: "Integrated mobility for 94,000 attendees \u00B7 Carbon-smart routing", children: _jsxs(motion.div, { variants: containerVariants, initial: "hidden", animate: "visible", className: "grid grid-cols-12 gap-5", children: [_jsxs("div", { className: "col-span-12 md:col-span-8 space-y-5", children: [_jsx(motion.div, { variants: containerVariants, className: "grid grid-cols-4 gap-3", children: modes.map(({ id, icon: Icon, label }) => (_jsxs(motion.button, { variants: itemVariants, whileHover: { y: -4, scale: 1.03 }, whileTap: { scale: 0.97 }, onClick: () => setMode(id), className: `flex flex-col items-center gap-2.5 p-4 rounded-2xl border transition-all ${mode === id ? "" : "glass border-indigo-500/[0.06] text-slate-400 hover:text-white"}`, style: mode === id ? {
                                    background: "rgba(99,102,241,0.1)",
                                    border: "1px solid rgba(99,102,241,0.3)",
                                    color: "#a5b4fc",
                                    boxShadow: "0 0 20px rgba(99,102,241,0.1)"
                                } : {}, children: [_jsx(Icon, { size: 22 }), _jsx("span", { className: "text-sm font-semibold font-display", children: label })] }, id))) }), _jsx(motion.div, { variants: slideUp, children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h3", { className: "font-display text-white font-semibold", children: "Available Departures" }), _jsx(LiveBadge, {})] }), _jsx("div", { className: "space-y-3", children: departures.map((opt, i) => (_jsxs(motion.div, { whileHover: { x: 4 }, className: "p-4 glass rounded-xl border border-indigo-500/[0.06] hover:border-indigo-500/[0.2] transition-all cursor-pointer", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-indigo-400" }), _jsx("span", { className: "font-display text-white font-semibold", children: opt.line })] }), _jsxs(Badge, { color: opt.crowd === "high" ? "red" : opt.crowd === "medium" ? "amber" : "green", children: [opt.crowd, " crowd"] })] }), _jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsxs("div", { className: "text-slate-500 font-mono-code text-xs", children: ["From ", opt.from] }), _jsxs("div", { className: "flex items-center gap-3 font-mono-code text-xs", children: [_jsxs("span", { children: ["Dep ", _jsx("span", { className: "text-white font-bold", children: opt.dep })] }), _jsx(ArrowRight, { size: 10, className: "text-slate-600" }), _jsxs("span", { children: ["Arr ", _jsx("span", { className: "text-emerald-400 font-bold", children: opt.arr })] })] })] }), _jsxs("div", { className: "flex items-center gap-2 mt-2", children: [_jsxs(Badge, { color: "green", children: [_jsx(Leaf, { size: 9 }), " Low carbon"] }), _jsx("span", { className: "text-xs text-slate-600 font-mono-code", children: "27 min journey" })] })] }, i))) })] }) })] }), _jsxs("div", { className: "col-span-12 md:col-span-4 space-y-4", children: [_jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Leaf, { size: 14, className: "text-emerald-400" }), _jsx("h3", { className: "font-display text-white font-semibold text-sm", children: "Carbon Footprint" })] }), [
                                        { mode: "Metro", kg: 0.3, color: "#10b981" },
                                        { mode: "Bus", kg: 0.6, color: "#6366f1" },
                                        { mode: "Ride Share", kg: 2.1, color: "#f59e0b" },
                                        { mode: "Private Car", kg: 4.8, color: "#ef4444" },
                                    ].map(({ mode: m, kg, color }) => (_jsxs("div", { className: "mb-3", children: [_jsxs("div", { className: "flex justify-between text-xs mb-1", children: [_jsx("span", { className: "text-slate-500", children: m }), _jsxs("span", { className: "text-white font-bold font-mono-code", children: [kg, " kg CO\u2082"] })] }), _jsx("div", { className: "h-1.5 rounded-full", style: { background: `${color}15` }, children: _jsx(motion.div, { initial: { width: 0 }, animate: { width: `${(kg / 4.8) * 100}%` }, transition: { duration: 1, ease: "easeOut", delay: 0.3 }, className: "h-full rounded-full", style: { background: color } }) })] }, m)))] }) }), _jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-5", children: [_jsx("h3", { className: "font-display text-white font-semibold text-sm mb-3", children: "Parking Availability" }), [
                                        { zone: "P1 — VIP", avail: "Full", color: "red" },
                                        { zone: "P2 — West", avail: "12 spots", color: "amber" },
                                        { zone: "P3 — South", avail: "234 spots", color: "green" },
                                        { zone: "P4 — Accessible", avail: "48 spots", color: "green" },
                                    ].map(({ zone, avail, color }) => (_jsxs("div", { className: "flex items-center justify-between py-2 border-b border-indigo-500/[0.06] last:border-0", children: [_jsx("span", { className: "text-sm text-slate-400", children: zone }), _jsx(Badge, { color: color, children: avail })] }, zone)))] }) }), _jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-5", style: { border: "1px solid rgba(99,102,241,0.2)" }, children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(Clock, { size: 14, className: "text-indigo-400" }), _jsx("span", { className: "font-display text-white font-semibold text-sm", children: "Estimated Travel" })] }), _jsxs("div", { className: "font-display text-3xl font-black gradient-text-indigo mb-1 font-mono-code", children: ["27 ", _jsx("span", { className: "text-lg text-slate-600 font-sans", children: "min" })] }), _jsx("div", { className: "text-xs text-slate-500 font-mono-code mb-3", children: "Via Metro Red Line from your location" }), _jsx("div", { className: "p-3 rounded-xl text-xs text-indigo-300 font-mono-code", style: { background: "rgba(99,102,241,0.06)", border: "1px solid rgba(99,102,241,0.12)" }, children: "\u26A1 Leave by 17:15 to arrive before kickoff" })] }) })] })] }) }));
}
