import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion } from "motion/react";
import { Bell, ChevronRight, Zap, Package, Heart, MapPin, CheckSquare, Clipboard } from "lucide-react";
import { containerVariants, itemVariants, slideUp } from "../shared/animations";
import { Badge, GlassCard, PremiumButton } from "../shared/primitives";
import { AppLayout } from "../shared/layout";
import { volunteerTasks, } from "../data/mockData";
// ─── VOLUNTEER DASHBOARD ───
export function VolunteerDashboard({ setPage }) {
    const [taskStates, setTaskStates] = useState(Object.fromEntries(volunteerTasks.map(t => [t.id, t.status])));
    return (_jsx(AppLayout, { page: "volunteer", setPage: setPage, title: "Volunteer Hub", subtitle: "Hi, Alex \u00B7 Zone C \u00B7 Shift 14:00\u201320:00", children: _jsxs(motion.div, { variants: containerVariants, initial: "hidden", animate: "visible", className: "grid grid-cols-12 gap-5", children: [_jsxs("div", { className: "col-span-12 md:col-span-8 space-y-5", children: [_jsx(motion.div, { variants: slideUp, children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h3", { className: "font-display text-white font-semibold", children: "Assigned Tasks" }), _jsxs(Badge, { color: "indigo", children: [volunteerTasks.filter(t => taskStates[t.id] !== "completed").length, " pending"] })] }), _jsx(motion.div, { variants: containerVariants, className: "space-y-2.5", children: volunteerTasks.map((task, i) => {
                                            const done = taskStates[task.id] === "completed";
                                            return (_jsx(motion.div, { variants: itemVariants, className: `p-4 rounded-xl border transition-all duration-300 ${done
                                                    ? "border-emerald-500/10 opacity-50"
                                                    : "border-indigo-500/[0.08] hover:border-indigo-500/[0.2] glass"}`, children: _jsxs("div", { className: "flex items-start gap-3", children: [_jsx(motion.button, { whileHover: { scale: 1.1 }, whileTap: { scale: 0.9 }, onClick: () => setTaskStates(s => ({ ...s, [task.id]: done ? "pending" : "completed" })), className: `mt-0.5 w-5 h-5 rounded-md border-2 flex items-center justify-center flex-shrink-0 transition-all ${done ? "border-emerald-500" : "border-slate-600 hover:border-indigo-500"}`, style: done ? { background: "#10b981" } : {}, children: done && _jsx(CheckSquare, { size: 11, className: "text-white" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("div", { className: `text-sm font-medium ${done ? "line-through text-slate-600" : "text-white"}`, children: task.task }), _jsxs("div", { className: "flex items-center gap-3 mt-1.5", children: [_jsxs("span", { className: "text-xs text-slate-600 font-mono-code flex items-center gap-1", children: [_jsx(MapPin, { size: 9 }), task.zone] }), _jsx(Badge, { color: task.priority === "high" ? "red" : task.priority === "medium" ? "amber" : "slate", children: task.priority })] })] })] }) }, task.id));
                                        }) })] }) }), _jsx(motion.div, { variants: slideUp, children: _jsxs(GlassCard, { className: "p-5", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Clipboard, { size: 15, className: "text-indigo-400" }), _jsx("h3", { className: "font-display text-white font-semibold", children: "SOP Quick Reference" })] }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: [
                                            { title: "Crowd Surge Protocol", steps: ["Stay calm, broadcast alert", "Open auxiliary exits", "Contact security team", "Document incident"] },
                                            { title: "Medical Response", steps: ["Call medical radio", "Keep area clear", "Guide paramedics", "Complete incident form"] },
                                        ].map(({ title, steps }) => (_jsxs("div", { className: "glass rounded-xl p-4 border border-indigo-500/[0.06]", children: [_jsx("div", { className: "text-sm font-display font-semibold text-white mb-3", children: title }), steps.map((s, i) => (_jsxs("div", { className: "flex items-start gap-2 mb-1.5", children: [_jsxs("span", { className: "text-xs text-indigo-400 font-mono-code font-bold mt-0.5", children: [i + 1, "."] }), _jsx("span", { className: "text-xs text-slate-500", children: s })] }, i)))] }, title))) })] }) })] }), _jsxs("div", { className: "col-span-12 md:col-span-4 space-y-4", children: [_jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-5", style: { border: "1px solid rgba(99,102,241,0.2)" }, children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx("div", { className: "w-7 h-7 rounded-lg flex items-center justify-center", style: { background: "linear-gradient(135deg, #6366f1, #4f46e5)" }, children: _jsx(Zap, { size: 13, className: "text-white" }) }), _jsx("span", { className: "font-display text-white font-semibold text-sm", children: "AI Copilot" })] }), _jsx("div", { className: "glass rounded-xl p-3 mb-3 border border-indigo-500/[0.08]", children: _jsx("p", { className: "text-slate-400 text-sm leading-relaxed", children: "Gate C queue at 540 people \u2014 suggest redirecting fans through Gate D. Your zone has capacity." }) }), _jsxs("div", { className: "flex gap-2", children: [_jsx(PremiumButton, { variant: "primary", size: "sm", className: "flex-1 justify-center", children: "Accept" }), _jsx(PremiumButton, { variant: "ghost", size: "sm", className: "flex-1 justify-center", children: "Dismiss" })] })] }) }), [
                            { icon: Package, label: "Lost & Found", color: "#f59e0b" },
                            { icon: Heart, label: "Medical Request", color: "#ef4444" },
                            { icon: Bell, label: "Emergency Alert", color: "#ef4444" },
                        ].map(({ icon: Icon, label, color }, i) => (_jsx(motion.div, { variants: itemVariants, children: _jsxs(motion.button, { whileHover: { scale: 1.02, y: -2 }, whileTap: { scale: 0.98 }, className: "w-full flex items-center gap-3 p-4 rounded-2xl border transition-all cursor-pointer", style: { background: `${color}06`, border: `1px solid ${color}20` }, children: [_jsx(Icon, { size: 17, style: { color } }), _jsx("span", { className: "font-display font-medium text-sm", style: { color: color + "cc" }, children: label }), _jsx(ChevronRight, { size: 13, className: "ml-auto text-slate-600" })] }) }, label))), _jsx(motion.div, { variants: itemVariants, children: _jsxs(GlassCard, { className: "p-5", children: [_jsx("div", { className: "font-display text-white font-semibold text-sm mb-3", children: "My Status" }), [["Shift", "14:00–20:00"], ["Zone", "Gate C / C1"], ["Supervisor", "Omar Al-Rashid"], ["Radio", "Channel 7"]].map(([k, v]) => (_jsxs("div", { className: "flex justify-between py-2 border-b border-indigo-500/[0.06] last:border-0", children: [_jsx("span", { className: "text-xs text-slate-600 font-mono-code", children: k }), _jsx("span", { className: "text-xs text-white font-medium", children: v })] }, k)))] }) })] })] }) }));
}
